name: Release new version

on:
  push:
    tags:
    - 'v*'

jobs:
  create-gh-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        # as electron-builder needs draft to upload artifacts, create once
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true

  release-electron:
    needs: create-gh-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, ubuntu-18.04, windows-2019]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '10'

      - name: Install libs on ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt install -y libusb-1.0-0-dev libudev-dev

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Build and Release
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Attach application to release
        run: gh release upload ${{ github.ref }} build/*.* --clobber
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
